@startuml
'ユーザー'
package devise {
    entity users{
        サロンメンバー
        --
        + ID
        ..
        email: String
        password: String
        name: String
        gender: Enum[man, woman]
        age: String
        residence: String
        employment_form: Enum[full_time, diff_full_time, side_biz, freelance, leave]
        github: String
        twitter: String
        facebook: String
        instagram: String
        portfolio_url: String
        zasetsu_count: Int
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }
}

package サロンメンバー検索アプリ {
    'スキル'
    entity skill_categories {
        スキル属性
        --
        + ID
        ..
        name: String
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }

    '技術'
    entity skill_sets {
        スキルセット(使用言語, FW, ソフトなど)
        --
        + ID
        ..
        # skill_categories_id [FK]
        name: String
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }

    'ユーザーとスキルカテゴリーの中間テーブル'
    entity user_and_skill_category_relationships {
        ユーザーとスキル属性の中間テーブル
        --
        + ID
        ..
        # user_id [FK]
        # skill_categories_id [FK]
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }

    'ユーザーとスキルセットの中間テーブル'
    entity user_and_skill_sets_relationships {
        ユーザーとスキルセットの中間テーブル
        --
        + ID
        ..
        # user_id [FK]
        # skill_sets_id [FK]
        level: Enum[junior, middle, veteran]
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }
}

users --|{ user_and_skill_category_relationships
skill_categories --|{ user_and_skill_category_relationships

users --|{ user_and_skill_sets_relationships
skill_sets --|{ user_and_skill_sets_relationships

skill_categories --|{ skill_sets

@enduml
