@startuml
'ユーザー'
package devise {
    entity users{
        サロンメンバー
        --
        + ID
        ..
        email [メールアドレス]: String, null: false
        password [パスワード]: String, null: false
        name [名前]: String, null: false
        gender [性別]: Enum[man, woman, other, not], null: false
        age [年代]: String
        residence [居住地]: String
        employment_form [就業形態]: Enum[full_time, diff_full_time, side_biz, freelance, leave], null: false
        github [GitHubのアカウント]: String
        twitter [Twitterのアカウント]: String
        facebook[Facebookのアカウント]: String
        instagram [Instagramのアカウント]: String
        portfolio_url [ポートフォリオのURL]: String
        zasetsu_count [挫折カウント]: Int
        created_at: Datetime
        updated_at: Datetime
        deleted_at: Datetime
    }
}

package サロンメンバー検索アプリ {
    'スキル'
    entity skill_categories {
        スキル属性
        --
        + ID
        ..
        name [スキル属性]: String, null: false
        created_at: Datetime, null: false
        updated_at: Datetime, null: false
        deleted_at: Datetime
    }

    '技術'
    entity skill_sets {
        スキルセット(使用言語, FW, ソフトなど)
        --
        + ID
        ..
        # skill_categories_id [FK]
        name: String
        created_at: Datetime, null: false
        updated_at: Datetime, null: false
        deleted_at: Datetime
    }

    'ユーザーとスキルカテゴリーの中間テーブル'
    entity user_and_skill_category_relationships {
        ユーザーとスキル属性の中間テーブル
        --
        + ID
        ..
        # user_id [FK], null: false
        # skill_categories_id [FK], null: false
        created_at: Datetime, null: false
        updated_at: Datetime, null: false
        deleted_at: Datetime
    }

    'ユーザーとスキルセットの中間テーブル'
    entity user_and_skill_sets_relationships {
        ユーザーとスキルセットの中間テーブル
        --
        + ID
        ..
        # user_id [FK], null: false
        # skill_sets_id [FK], null: false
        level [スキルレベル]: Enum[junior, middle, veteran], null: false
        created_at: Datetime, null: false
        updated_at: Datetime, null: false
        deleted_at: Datetime
    }
}

users --|{ user_and_skill_category_relationships
skill_categories --|{ user_and_skill_category_relationships

users --|{ user_and_skill_sets_relationships
skill_sets --|{ user_and_skill_sets_relationships

skill_categories --|{ skill_sets

@enduml
